version: "2.2"
services:
  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - cert_network
  keycloack:
    image: quay.io/keycloak/keycloak:10.0.1
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=postgres
    ports:
      - 8090:8080
    depends_on:
      - "postgres"
    networks:
      - cert_network
networks:
  cert_network:
    name: cert_network
